Algoritmo "032"

Var
    num, palpite: Inteiro


Inicio
      Escreval("------------------------")
      Escreval("      Me adivinhe!      ")
      Escreval("------------------------")
      Leia(num)
      Escreva("Digite um palpite: ")
      Leia(palpite)
      
           Se palpite = num entao
                Escreval("Voce acertou!")
                senao
                Escreval("Voce errou!")
           FimSe


Fimalgoritmo