Algoritmo "071"
// Preenchimento automatico de valores em um vetor
Var
   num: vetor[1..8] de inteiro
   i: Inteiro


Inicio
      Escreval("---------------------------------------------------")

      Para i <- 1 ate 8 faca
      leia(num[i])

      FimPara

              Para i <- 1 ate 8 faca
                   Escreva("[", num[i], "]")

              FimPara

       Escreval()
       Escreval("---------------------------------------------------")









Fimalgoritmo