Algoritmo "073"
// Adicionar números em um vetor
Var
      num: vetor[1..10] de inteiro
      i: Inteiro


Inicio
       Escreval("---------------------------------------------------")

       Para i <- 10 ate 1 passo -1 faca
       num[i] <- i - 1
              Escreva("[", num[i], "]")
       FimPara

       Escreval()
       Escreval("---------------------------------------------------")
Fimalgoritmo