Algoritmo "012"
// desconto de 10% em um produto
Var
    preco, precodesc: Real


Inicio
      Escreval("------------------------------")
      Escreval("Qual o valor do seu produto?:")
      Escreval("------------------------------")
      Leia(preco)
      
      precodesc <- preco - (preco * 0.10)
      
      Escreval("O preço do produto com desconto foi de:", precodesc)
      
      


Fimalgoritmo