Algoritmo "048"

Var
     num, vezes, somanum: Inteiro


Inicio
      Escreval("Leia 7 números!")
      vezes <- 0
      
      Enquanto (vezes < 7) faca
               Leia(num)
               
               somanum <- somanum + num
               
               vezes <- vezes + 1
               
      
      FimEnquanto
      
      Escreval("A soma dos números, é igual a ", somanum)


Fimalgoritmo