Algoritmo "009"
// Conversor de doláres para reais
Var
   reais, dol: Real


Inicio
    Escreval("------------------------------------------")
    Escreval("       Conversor de R$ para US$           ")
    Escreval("------------------------------------------")
    Escreva("Digite seus valores em R$:")
    Leia(reais)
    
    dol <- reais / 3,45
    
    Escreval("------------------------------------------")
    Escreval("Seu valor em doláres é igual a US$:", dol   )
    Escreval("------------------------------------------")
    


Fimalgoritmo