Algoritmo "020"

Var
      num: inteiro


Inicio
      Escreval("---------------------------")
      Escreval("       Par ou Impar        ")
      Escreval("---------------------------")
      Escreva(" Digite um número:")
      Leia(num)
      Escreval("---------------------------")
      
      Se num % 2 = 0 entao
          Escreval("O número ", num, " é par")
      senao
          Escreval("O número ", num, " é impar")
      FimSe


Fimalgoritmo